### ISSUE TITLE
Error getting IP Address for service{maya-apiserver-service}

### ISSUE THREAD

**Issue by gridworkz** [vitobotta/velero-openebs-backup#1]
btw: Great scripts - they're a real time saver. I get 3 error messages when I try a backup:

1) Error getting IP Address for service{maya-apiserver-service} : services \"maya-apiserver-service\" not found...

2) Error getting volume snapshotter for volume snapshot location" backup=velero/contastico error="rpc error: code = Unknown desc = Error fetching OpenEBS rest client address...

3) Error getting volume snapshotter for volume snapshot location" backup=velero/contastico error="rpc error: code = Unknown desc = missing region in aws configuration

Here's my backup location file:

`---`
`apiVersion: velero.io/v1`
`kind: BackupStorageLocation`
`metadata:`
    `  name: default`
    `  namespace: velero`
`spec:`
    `  provider: aws`
    `  objectStorage:`
    `    bucket: velero`
    `  config:`
    `    s3Url: https://bkp.contastico.com`
    `    s3ForcePathStyle: "true"`
    `    region: minio`

- How do I get the maya-apiserver-service installed?
- I do specify a region in my backup storage location file
- #2 may be related to #1

I've got a thread going at Slack /w OpenEBS guys: https://openebs-community.slack.com/messages/GL689PWKG/convo/C3NPGQ6G3-1560876105.305900/

**Comment by gridworkz** [comment]
All good now -

**Comment by rohansadale** [comment]
I am hitting this issue. How was it resolved?

**Comment by elifish4** [comment]
+1
@gridworkz, Can you share how it was resolved?

**Comment by gridworkz** [comment]
Sorry guys I ended up going a different route.
